import type { Metadata } from "next";
import React from "react";
import classNames from "classnames";
import ThemeProvider from "./theme/themeProvider";
import "./variables.scss";
import "./globals.scss";
import Navigator from "@/components/Navbar";
import localFont from "next/font/local";
import { CssBaseline } from "@mui/material";

const localInter = localFont({ src: "./fonts/inter.ttf", display: "auto" });

export const metadata: Metadata = {
  title: "Dexta Labs",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: { apple: "/icon.png" },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider>
      <html lang="en">
        <head>
          <link rel="stylesheet" type="text/css" href="./globals.scss"></link>
        </head>
        <body
          className={classNames(
            localInter.className,
            " bg-whitePurple overflow-auto flex"
          )}
        >
          <Navigator />
          <div className="flex-1">{children}</div>
        </body>
      </html>
    </ThemeProvider>
  );
}
