import type { Metadata } from "next";
import React from "react";
import classNames from "classnames";
import ThemeProvider from "./theme/themeProvider";
import "./variables.scss";
import "./globals.scss";
import localFont from "next/font/local";
import WithNav from "./hoc/WithNav";
import axios from "axios";

const localInter = localFont({ src: "./fonts/inter.ttf", display: "auto" });

export const metadata: Metadata = {
  title: "Dexta Labs",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: { apple: "/icon.png" },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const getToken = async () => {
    try {
      const res = await axios.get("http://localhost:3000/api/getToken");
    } catch (err) {}
  };

  const token = await getToken();

  return (
    <ThemeProvider>
      <html lang="en">
        <body
          className={classNames(
            localInter.className,
            " bg-whitePurple overflow-auto flex"
          )}
        >
          <WithNav>{children}</WithNav>
        </body>
      </html>
    </ThemeProvider>
  );
}
