import classNames from "classnames";
import type { Metadata } from "next";
import localFont from "next/font/local";
import React from "react";
import WithAuth from "../provider/hoc/WithAuth";
import WithNav from "../provider/hoc/WithNav";
import ThemeProvider from "../provider/theme/themeProvider";
import "./globals.scss";
import "./variables.scss";

const localInter = localFont({ src: "./fonts/inter.ttf", display: "auto" });

export const metadata: Metadata = {
  title: "Dexta Labs",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: { apple: "/icon.png" },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body
          className={classNames(
            localInter.className,
            " bg-whitePurple overflow-auto flex"
          )}
        >
          <WithAuth>
            <WithNav>{children}</WithNav>
          </WithAuth>
        </body>
      </html>
    </ThemeProvider>
  );
}
